// flow-typed signature: 7ad7d39a65fd2d233a6a0b5f3b8766a2
// flow-typed version: <<STUB>>/gatsby-plugin-postcss_v^2.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-postcss/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-postcss/resolve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-postcss/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-postcss/gatsby-node'>;
}
declare module 'gatsby-plugin-postcss/index' {
  declare module.exports: $Exports<'gatsby-plugin-postcss'>;
}
declare module 'gatsby-plugin-postcss/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-postcss'>;
}
declare module 'gatsby-plugin-postcss/resolve.js' {
  declare module.exports: $Exports<'gatsby-plugin-postcss/resolve'>;
}
