// flow-typed signature: ec06e28f415f28549a4a233d91eb5cba
// flow-typed version: <<STUB>>/gatsby-plugin-react-next_v^1.0.11/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-react-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-react-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-react-next/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-react-next/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-react-next/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-next/gatsby-browser'>;
}
declare module 'gatsby-plugin-react-next/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-next/gatsby-node'>;
}
declare module 'gatsby-plugin-react-next/index' {
  declare module.exports: $Exports<'gatsby-plugin-react-next'>;
}
declare module 'gatsby-plugin-react-next/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-next'>;
}
