// flow-typed signature: 1b6d5861540b39eb8dc15dd495c1b36f
// flow-typed version: <<STUB>>/@getatomi/eslint-config_v^1.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@getatomi/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@getatomi/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@getatomi/eslint-config/index' {
  declare module.exports: $Exports<'@getatomi/eslint-config'>;
}
declare module '@getatomi/eslint-config/index.js' {
  declare module.exports: $Exports<'@getatomi/eslint-config'>;
}
